version: 1.0
setup:
  - name: "Install dependencies"
    command: "go mod tidy"

steps:
  - name: "Build binary"
    command: "go build -o cicd-go ./cmd"

post_build:
  - name: "Moving binary"
    command: "mv cicd-go output/cicd-go"
  - name: "Copying binary to global path"
    command: "cp output/cicd-go /usr/local/bin"
    if: "env.GLOBAL == 'true'"

ignore:
  - "output/"
  - ".git"
  - "*.log"
  - "build.yaml"
  - "readme.md"